import { AppData } from "../types";
import { cloneDefaultAllowedTaRules } from "../lib/utils/allowed-ta-rules";

export const INITIAL_APP_DATA: AppData = {
  Timesheet_InputList: [],
  Final_AE: {
    headers: [
      "No",
      "Mã AE",
      "Business",
      "ID Number",
      "Full name",
      "TOTAL PAYMENT",
    ],
    data: [],
  },
  Bank_North_AE: {
    headers: [
      "No",
      "L07",
      "Business",
      "ID Number",
      "Full name",
      "Bank Account Number",
      "TOTAL PAYMENT",
      "LOẠI CK",
      "Payment details",
    ],
    data: [],
  },
  Sheet1_AE: {
    headers: [
      "No.",
      "Tháng báo cáo",
      "L07",
      "Business",
      "ID Number",
      "Full name",
      "Salary Scale",
      "From",
      "To",
      "Bank Account Number",
      "Bank Name",
      "CITAD code",
      "TAX CODE",
      "Contract No",
      "CHARGE TO LXO",
      "CHARGE TO EC",
      "CHARGE TO PT-DEMO",
      "Charge MKT Local",
      "CHARGE TO OTHER",
      "Charge Renewal Projects",
      "Charge Discovery Camp",
      "Charge Summer Outing",
      "Charge Summer Instructors",
      "Extra Summer Instructors",
      "TOTAL PAYMENT",
      "TÊN FILE",
      "Center",
    ],
    data: [],
  },
  Hold_AE: {
    headers: [
      "No.",
      "TÊN FILE",
      "Tháng báo cáo",
      "BU",
      "L07",
      "ID Number",
      "Full name",
      "Bank Account Number",
      "TAX CODE",
      "Contract No",
      "TOTAL PAYMENT",
      "Sheet Source",
      "Note",
      "Nghiệp vụ",
      "Tháng phát sinh",
      "Mã ae",
    ],
    data: [],
  },
  SoSanh_AE: {
    headers: [
      "ID Number",
      "Full name",
      "Sheet 1 AE",
      "Bank North AE",
      "Chênh Lệch",
    ],
    data: [],
  },
  AuditReport: {
    headers: [
      "Khóa Cột So Sánh",
      "Mã AE",
      "Total (Bảng 1)",
      "Total (Bảng 2)",
      "Chênh Lệch",
    ],
    data: [],
  },
  BankExport: {
    headers: [
      "Payment Serial Number",
      "Tháng báo cáo",
      "Transaction Type Code",
      "Payment Type",
      "Customer Reference No",
      "Beneficiary Account No.",
      "Beneficiary Name",
      "Document ID",
      "Place of Issue",
      "ID Issuance Date",
      "Beneficiary Bank Swift Code / IFSC Code",
      "Transaction Currency",
      "Payment Amount",
      "Charge Type",
      "Payment details",
      "Beneficiary - Nick Name",
      "Beneficiary Addr. Line 1",
      "Beneficiary Addr. Line 2",
    ],
    data: [],
  },
  CustomReport: {
    headers: ["No.", "Trung Tâm", "Tháng", "Tổng tiền", "Ghi chú"],
    data: [],
  },
  AE_Map: {},
  AE_AutoMappingRules: [],
  Ae_Global_Inputs: [],
  PivotConfig: {
    headers: { Business: "Business", L07: "L07", GRAND_TOTAL: "GRAND TOTAL" },
    chargeCols: [
      { key: "CHARGE TO LXO", label: "CHARGE TO LXO", code: "04" },
      { key: "CHARGE TO EC", label: "CHARGE TO EC", code: "PSZINT-A1" },
      {
        key: "CHARGE TO PT-DEMO",
        label: "CHARGE TO PT-DEMO",
        code: "MAZINT-E1-LDEM01",
      },
      { key: "Charge MKT Local", label: "CHARGE MKT LOCAL", code: "E1" },
      { key: "CHARGE TO OTHER", label: "CHARGE OTHER", code: "" },
      {
        key: "Charge Renewal Projects",
        label: "CHARGE RENEWAL PROJECTS",
        code: "EFZZZZ-R3",
      },
      {
        key: "Charge Discovery Camp",
        label: "CHARGE DISCOVERY CAMP",
        code: "",
      },
      { key: "Charge Summer Outing", label: "CHARGE SUMMER OUTING", code: "" },
      { key: "Charge Summer Instructors", label: "CHARGE SUMMER INSTRUCTORS", code: "" },
      { key: "Extra Summer Instructors", label: "EXTRA SUMMER INSTRUCTORS", code: "" },
    ],
  },
  Q_Staff: [],
  Q_Salary_Scale: [],
  Master_Roster: [],
  Timesheet_Roster: [
    {
      _rowId: "mock-row-1",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT NA",
      l07: "MKT LOCAL NORTH",
      business: "AHN",
      ma_nv: "NV001",
      full_name: "Nguyễn Văn Sơn",
      ngay: "2026-06-01",
      type: "In Class",
      class: "ECP_A1_01",
      gio_vao: "08:00",
      gio_ra: "10:00",
      duration: 2,
      notes: "Giảng dạy lớp sáng",
      employeeId: "NV001",
      fullName: "Nguyễn Văn Sơn",
      maAE: "MKT NA",
      date: "2026-06-01",
      taskType: "In Class",
      classCode: "ECP_A1_01",
      from: "08:00",
      to: "10:00"
    },
    {
      _rowId: "mock-row-2",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT BN",
      l07: "MKT LOCAL NORTH",
      business: "AHN",
      ma_nv: "NV002",
      full_name: "Trần Thị Lan",
      ngay: "2026-06-01",
      type: "Tutoring",
      class: "ECP_B2_03",
      gio_vao: "10:30",
      gio_ra: "12:00",
      duration: 1.5,
      notes: "Phụ đạo học sinh yếu",
      employeeId: "NV002",
      fullName: "Trần Thị Lan",
      maAE: "MKT BN",
      date: "2026-06-01",
      taskType: "Tutoring",
      classCode: "ECP_B2_03",
      from: "10:30",
      to: "12:00"
    },
    {
      _rowId: "mock-row-3",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT TH01.TPU",
      business: "ATH",
      ma_nv: "NV003",
      full_name: "Lê Minh Đức",
      ngay: "2026-06-02",
      type: "Admin",
      class: "OFFICE_WORK",
      gio_vao: "13:30",
      gio_ra: "15:30",
      duration: 2,
      notes: "Họp chuyên môn tuần",
      employeeId: "NV003",
      fullName: "Lê Minh Đức",
      maAE: "MKT TH01.TPU",
      date: "2026-06-02",
      taskType: "Admin",
      classCode: "OFFICE_WORK",
      from: "13:30",
      to: "15:30"
    },
    {
      _rowId: "mock-row-4",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT TN01.LNQ",
      business: "ATN",
      ma_nv: "NV004",
      full_name: "Phạm Hồng Hạnh",
      ngay: "2026-06-02",
      type: "Club Activity",
      class: "ENGLISH_CLUB_01",
      gio_vao: "16:00",
      gio_ra: "17:30",
      duration: 1.5,
      notes: "Hoạt động câu lạc bộ tiếng Anh",
      employeeId: "NV004",
      fullName: "Phạm Hồng Hạnh",
      maAE: "MKT TN01.LNQ",
      date: "2026-06-02",
      taskType: "Club Activity",
      classCode: "ENGLISH_CLUB_01",
      from: "16:00",
      to: "17:30"
    },
    {
      _rowId: "mock-row-5",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT VP",
      l07: "MKT LOCAL NORTH",
      business: "AHN",
      ma_nv: "NV005",
      full_name: "Hoàng Thanh Tùng",
      ngay: "2026-06-03",
      type: "In Class",
      class: "IELTS_65_02",
      gio_vao: "18:00",
      gio_ra: "20:00",
      duration: 2,
      notes: "Dạy lớp IELTS tối",
      employeeId: "NV005",
      fullName: "Hoàng Thanh Tùng",
      maAE: "MKT VP",
      date: "2026-06-03",
      taskType: "In Class",
      classCode: "IELTS_65_02",
      from: "18:00",
      to: "20:00"
    },
    {
      _rowId: "mock-row-6",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT QN",
      l07: "MKT LOCAL NORTH",
      business: "AHN",
      ma_nv: "NV006",
      full_name: "Vũ Thị Mai",
      ngay: "2026-06-03",
      type: "Demo",
      class: "DEMO_CLASS_01",
      gio_vao: "09:00",
      gio_ra: "10:30",
      duration: 1.5,
      notes: "Dạy thử học sinh mới",
      employeeId: "NV006",
      fullName: "Vũ Thị Mai",
      maAE: "MKT QN",
      date: "2026-06-03",
      taskType: "Demo",
      classCode: "DEMO_CLASS_01",
      from: "09:00",
      to: "10:30"
    },
    {
      _rowId: "mock-row-7",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT HY",
      l07: "MKT LOCAL NORTH",
      business: "AHN",
      ma_nv: "NV007",
      full_name: "Đỗ Gia Bảo",
      ngay: "2026-06-04",
      type: "In Class",
      class: "KDG_B1_05",
      gio_vao: "15:00",
      gio_ra: "16:30",
      duration: 1.5,
      notes: "Dạy lớp mầm non",
      employeeId: "NV007",
      fullName: "Đỗ Gia Bảo",
      maAE: "MKT HY",
      date: "2026-06-04",
      taskType: "In Class",
      classCode: "KDG_B1_05",
      from: "15:00",
      to: "16:30"
    },
    {
      _rowId: "mock-row-8",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT HN",
      l07: "MKT LOCAL NORTH",
      business: "AHN",
      ma_nv: "NV008",
      full_name: "Bùi Minh Tuấn",
      ngay: "2026-06-04",
      type: "Admin",
      class: "PREPARATION",
      gio_vao: "14:00",
      gio_ra: "15:00",
      duration: 1,
      notes: "Chuẩn bị giáo án",
      employeeId: "NV008",
      fullName: "Bùi Minh Tuấn",
      maAE: "MKT HN",
      date: "2026-06-04",
      taskType: "Admin",
      classCode: "PREPARATION",
      from: "14:00",
      to: "15:00"
    },
    {
      _rowId: "mock-row-9",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT PT01.HVG",
      business: "APT",
      ma_nv: "NV009",
      full_name: "Ngô Quốc Khánh",
      ngay: "2026-06-05",
      type: "In Class",
      class: "PRI_C3_02",
      gio_vao: "08:30",
      gio_ra: "10:30",
      duration: 2,
      notes: "Dạy lớp Tiểu học",
      employeeId: "NV009",
      fullName: "Ngô Quốc Khánh",
      maAE: "MKT PT01.HVG",
      date: "2026-06-05",
      taskType: "In Class",
      classCode: "PRI_C3_02",
      from: "08:30",
      to: "10:30"
    },
    {
      _rowId: "mock-row-10",
      _sourceFile: "Mock_Roster.xlsx",
      center: "MKT HP",
      business: "AHP",
      ma_nv: "NV010",
      full_name: "Lý Mỹ Linh",
      ngay: "2026-06-05",
      type: "Tutoring",
      class: "ECP_A2_07",
      gio_vao: "14:00",
      gio_ra: "15:00",
      duration: 1,
      notes: "Kèm cặp học sinh thêm",
      employeeId: "NV010",
      fullName: "Lý Mỹ Linh",
      maAE: "MKT HP",
      date: "2026-06-05",
      taskType: "Tutoring",
      classCode: "ECP_A2_07",
      from: "14:00",
      to: "15:00"
    }
  ],
  Q_Cache: [],
  Timesheet_Dates: { from: "", to: "" },
  Timesheets: [],
  TA_Employee_Summary: { headers: [], data: [] },
  TA_Center_Summary: { headers: [], data: [] },
  Q_TeacherHours: [],
  Q_TeacherHoursFileName: "",
  Q_AllowedTARules: cloneDefaultAllowedTaRules(),
  Timesheet_RosterEditHistory: [],
};
