import { SalaryScaleDef } from "../types";

export const DEFAULT_SALARY_SCALES: Record<string, SalaryScaleDef> = {
  S1: { ac: 33000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  S2: { ac: 36000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  S3: { ac: 40000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  S4: { ac: 45000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  S5: { ac: 50000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  S6: { ac: 53000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  S7: { ac: 20000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  "S-CORP": { ac: 85714, ad: 0, summer: 29474, outing: 26316, summerInstructors: 150000 },
  SDN1: { ac: 32000, ad: 18000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  SDN2: { ac: 36000, ad: 18000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  SDN3: { ac: 40000, ad: 18000, summer: 29474, outing: 26316, summerInstructors: 150000 },
  SDN7: { ac: 20000, ad: 20000, summer: 29474, outing: 26316, summerInstructors: 150000 },
};

export const TASK_COLUMNS: Record<string, string> = {
  "in-class": "inClass",
  "in-class atls": "inClassAtls",
  demo: "demo",
  tutoring: "tutoring",
  "waiting class": "waitingClass",
  "club activity": "clubActivity",
  "parent meeting": "parentMeeting",
  pt: "pt",
  "placement test": "pt",
  "discovery camp": "discoveryCamp",
  outing: "outing",
  summer: "summer",
  "summer instructors": "summerInstructors",
  "pick up/ drop off": "pickUpDropOff",
  "pick up/ drop off atls": "pickUpDropOffAtls",
  sms: "sms",
  "sms atls": "smsAtls",
  "progress/gradebook report": "progressReport",
  "gradebook report atls": "progressReportAtls",
  "progress report": "progressReport",
  "progress report atls": "progressReportAtls",
  "prepare lesson - tutoring": "prepareLessonTutoring",
  "prepare lesson - clubs": "prepareLessonClubs",
  "meeting/ training": "meetingTraining",
  "conduct test": "conductTest",
  "renewal projects": "renewalProjects",
  "support lxo": "supportLxo",
  "support ec": "supportEc",
  "support mkt": "supportMkt",
  "charge to mkt local": "supportMkt",
  "charge mkt local": "supportMkt",
  "charge mkt": "supportMkt",
  "mkt local": "supportMkt",
  "charge other": "other",
  "charge to other": "other",
  other: "other",
  "charge to summer instructors": "summerInstructors",
  "charge summer instructors": "summerInstructors",
  "summer instructor": "summerInstructors",
  "charge instructor": "summerInstructors",
  "summer instructors (ak)": "summerInstructors",
  "charge lxo": "supportLxo",
  "charge to lxo": "supportLxo",
  lxo: "supportLxo",
  "charge ec": "supportEc",
  "charge to ec": "supportEc",
  ec: "supportEc",
  "charge pt-demo": "pt",
  "charge to pt-demo": "pt",
  "charge discovery camp": "discoveryCamp",
  "charge to discovery camp": "discoveryCamp",
  "charge summer outing": "outing",
  "charge to summer outing": "outing",
  "charge renewal projects": "renewalProjects",
  "charge to renewal projects": "renewalProjects",
  lpar: "lpar01",
  lpar01: "lpar01",
  ldem: "ldem01",
  ldem01: "ldem01",
  lret: "lret01",
  lret01: "lret01",
  ldec: "ldec01",
  ldec01: "ldec01",
  moth: "moth01",
  moth01: "moth01",
};

export const ACADEMIC_FIELDS = [
  "inClass",
  "inClassAtls",
  "demo",
  "tutoring",
  "waitingClass",
  "clubActivity",
  "parentMeeting",
];
