import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import type { SupabaseClient } from '@supabase/supabase-js';
import { preflightTimesheetSync, SQL_SETUP_SCRIPT } from '../src/app/lib/supabase-sync-utils';
import { describeSupabaseSyncError, SupabaseSchemaError } from '../src/app/lib/utils/supabase-sync-errors';

test('missing raw_data is reported as a column error with the correct table, not a nonexistent roster', () => {
  const error = describeSupabaseSyncError('roster_cham_cong', {code:'PGRST204', message:"Could not find the 'raw_data' column of 'roster_cham_cong' in the schema cache"});
  assert.ok(error instanceof SupabaseSchemaError);
  assert.match(error.message, /thiếu cột/);
  assert.match(error.message, /raw_data/);
  assert.ok(!error.message.includes('Không tìm thấy bảng'));
  assert.match(describeSupabaseSyncError('nhan_vien', {code:'PGRST205',message:'Missing table'}).message, /public.nhan_vien/);
  assert.ok(!(describeSupabaseSyncError('nhan_vien', {code:'23502',message:'null id of relation nhan_vien'}) instanceof SupabaseSchemaError));
  assert.ok(!(describeSupabaseSyncError('roster_cham_cong', {code:'42501',message:'permission denied'}) instanceof SupabaseSchemaError));
});

test('schema check detects raw_data before performing any write', async () => {
  const calls: string[] = [];
  const client = {from(table: string) {
    calls.push(table);
    return {select(columns: string) { assert.ok(columns.includes('raw_data'));
      return {limit: async () => ({error:{code:'42703',message:'column roster_cham_cong.raw_data does not exist'}})};
    }};
  }} as unknown as SupabaseClient;
  await assert.rejects(preflightTimesheetSync(['roster_cham_cong', 'nhan_vien'],client), SupabaseSchemaError);
  assert.deepEqual(calls, ['roster_cham_cong']);
});

test('roster migration repairs the existing schema and Setup supports both fresh and existing tables', async () => {
  const db = new PGlite();
  try {
    await db.exec(`create table public.roster_cham_cong (id bigint generated by default as identity primary key,
      ma_nv text, unique_id text unique); insert into public.roster_cham_cong(ma_nv, unique_id) values ('001','shift-1');`);
    const payload = {id:'local-1', chargeToCenterMkt:'NORTH', _pivotOverride:{hours:2}};
    await assert.rejects(db.query('update public.roster_cham_cong set raw_data=$1::jsonb where unique_id=$2', [JSON.stringify(payload), 'shift-1']), {code:'42703'});
    const sql = readFileSync(new URL('../supabase/migrations/20260909184211_roster_raw_data.sql', import.meta.url),'utf8');
    await db.exec(sql); await db.exec(sql);
    await db.query('update public.roster_cham_cong set raw_data=$1::jsonb where unique_id=$2', [JSON.stringify(payload),'shift-1']);
    assert.deepEqual((await db.query<{ma_nv:string;raw_data:unknown}>('select ma_nv,raw_data from public.roster_cham_cong')).rows, [{ma_nv:'001',raw_data:payload}]);
    await db.exec('drop table public.roster_cham_cong');
    await db.exec(SQL_SETUP_SCRIPT);
    await db.exec(SQL_SETUP_SCRIPT);
    const columns = (await db.query<{column_name:string}>("select column_name from information_schema.columns where table_schema='public' and table_name='roster_cham_cong'")).rows.map(item=>item.column_name);
    assert.ok(columns.includes('raw_data'));
    await db.query('insert into public.roster_cham_cong(ma_nv,unique_id,raw_data) values ($1,$2,$3::jsonb)', ['001','shift-1',JSON.stringify(payload)]);
    assert.deepEqual((await db.query('select raw_data from public.roster_cham_cong')).rows, [{raw_data:payload}]);
  } finally { await db.close(); }
});
