export const BASE_TASK_COLUMNS = [
  { key: "inClass", label: "In-class", type: "number" as const, width: 90, group: "Academic Hours" },
  { key: "inClassAtls", label: "In-class ATLS", type: "number" as const, width: 110, group: "Academic Hours" },
  { key: "demo", label: "Demo", type: "number" as const, width: 80, group: "Academic Hours" },
  { key: "tutoring", label: "Tutoring", type: "number" as const, width: 90, group: "Academic Hours" },
  { key: "waitingClass", label: "Waiting class", type: "number" as const, width: 110, group: "Academic Hours" },
  { key: "clubActivity", label: "Club activity", type: "number" as const, width: 110, group: "Academic Hours" },
  { key: "parentMeeting", label: "Parent meeting", type: "number" as const, width: 120, group: "Academic Hours" },
  { key: "pickUpDropOff", label: "Pick up/ Drop off", type: "number" as const, width: 140, group: "Admin Hours" },
  {
    key: "pickUpDropOffAtls",
    label: "Pick up/ Drop off ATLS",
    type: "number" as const,
    width: 170,
    headerSpanClassName: "text-[12px] leading-[18px]",
    group: "Admin Hours",
  },
  { key: "sms", label: "SMS", type: "number" as const, width: 80, group: "Admin Hours" },
  { key: "smsAtls", label: "SMS ATLS", type: "number" as const, width: 100, group: "Admin Hours" },
  {
    key: "progressReport",
    label: "Progress/Gradebook Report",
    type: "number" as const,
    width: 200,
    group: "Admin Hours",
  },
  {
    key: "progressReportAtls",
    label: "Gradebook Report ATLS",
    type: "number" as const,
    width: 200,
    headerSpanClassName: "leading-[18px] text-[12px] font-bold",
    group: "Admin Hours",
  },
  {
    key: "prepareLessonTutoring",
    label: "Prepare lesson - Tutoring",
    type: "number" as const,
    width: 190,
    group: "Admin Hours",
  },
  {
    key: "meetingTraining",
    label: "Meeting/ Training",
    type: "number" as const,
    width: 150,
    group: "Admin Hours",
  },
  { key: "pt", label: "PT", type: "number" as const, width: 80, group: "Admin Hours" },
  { key: "discoveryCamp", label: "Discovery Camp", type: "number" as const, width: 130, group: "Admin Hours" },
  { key: "outing", label: "Outing", type: "number" as const, width: 90, group: "Admin Hours" },
  { key: "summer", label: "Summer", type: "number" as const, width: 90, group: "Admin Hours" },
  {
    key: "summerInstructors",
    label: "Summer Instructors",
    type: "number" as const,
    width: 150,
    headerSpanClassName: "text-[11.2px] font-bold leading-[16.8px]",
    group: "Admin Hours",
  },
  {
    key: "prepareLessonClubs",
    label: "Prepare lesson - Clubs",
    type: "number" as const,
    width: 170,
    group: "Admin Hours",
  },
  { key: "conductTest", label: "Conduct test", type: "number" as const, width: 110, group: "Admin Hours" },
  {
    key: "renewalProjects",
    label: "Renewal Projects",
    type: "number" as const,
    width: 140,
    group: "Admin Hours",
  },
  { key: "supportLxo", label: "Support LXO", type: "number" as const, width: 110, group: "Admin Hours" },
  { key: "supportEc", label: "Support EC", type: "number" as const, width: 100, group: "Admin Hours" },
  { key: "supportMkt", label: "Support MKT", type: "number" as const, width: 110, group: "Admin Hours" },
  { key: "lpar01", label: "LPAR01", type: "number" as const, width: 90, group: "Admin Hours" },
  { key: "lret01", label: "LRET01", type: "number" as const, width: 90, group: "Admin Hours" },
  { key: "ldem01", label: "LDEM01", type: "number" as const, width: 90, group: "Admin Hours" },
  { key: "ldec01", label: "LDEC01", type: "number" as const, width: 90, group: "Admin Hours" },
  { key: "moth01", label: "MOTH01", type: "number" as const, width: 90, group: "Admin Hours" },
  { key: "totalHours", label: "Total Hours", type: "number" as const, width: 110, cellClassName: "font-black text-slate-900 bg-slate-50" },
  { key: "academicHours", label: "Academic Hours", type: "number" as const, width: 130, cellClassName: "font-bold text-accent bg-accent/10" },
  { key: "adminHours", label: "Admin Hours", type: "number" as const, width: 110, cellClassName: "font-bold text-accent bg-accent/20", headerSpanClassName: "text-xs no-underline leading-[11px] text-accent" },
  { key: "klHours", label: "KL Hours", type: "number" as const, width: 100, cellClassName: "font-bold text-rose-600 bg-rose-50" },
];
