import { supabase } from "@/lib/supabaseClient";
import {
  createStableTimesheetRowId,
  dedupeTimesheetRosterRows,
} from "./utils/timesheet-roster-utils";

export const SQL_SETUP_SCRIPT = `-- SQL setup script for Supabase
CREATE TABLE IF NOT EXISTS roster_cham_cong (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  l07 TEXT,
  center TEXT,
  business TEXT,
  ma_nv TEXT,
  full_name TEXT,
  ngay TEXT,
  type TEXT,
  class TEXT,
  gio_vao TEXT,
  gio_ra TEXT,
  duration NUMERIC,
  notes TEXT,
  charge_to_center_mkt TEXT,
  unique_id TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nhan_vien (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business TEXT,
  center TEXT,
  employee_id TEXT UNIQUE,
  full_name TEXT,
  bank_account_number TEXT,
  salary_scale TEXT,
  "from" TEXT,
  "to" TEXT,
  class_name TEXT,
  note_days TEXT,
  unique_id TEXT UNIQUE,
  raw_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS thang_luong (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s_code TEXT UNIQUE,
  academic_price NUMERIC,
  base_salary NUMERIC,
  total_salary NUMERIC,
  deduction_hours NUMERIC,
  unique_id TEXT UNIQUE,
  raw_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure column exists if table was already created
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='roster_cham_cong' AND column_name='charge_to_center_mkt') THEN
    ALTER TABLE roster_cham_cong ADD COLUMN charge_to_center_mkt TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='roster_cham_cong' AND column_name='center') THEN
    ALTER TABLE roster_cham_cong ADD COLUMN center TEXT;
  END IF;
END $$;

-- Drop obsolete constraint that restricts teachers to only one shift per day
ALTER TABLE roster_cham_cong DROP CONSTRAINT IF EXISTS unique_nv_ngay;

-- Drop foreign key constraint if it exists to prevent sync errors when rosters refer to unlisted staff
ALTER TABLE roster_cham_cong DROP CONSTRAINT IF EXISTS roster_cham_cong_ma_nv_fkey;

-- Row Level Security (RLS) - Allow ALL operations for anon role
ALTER TABLE roster_cham_cong ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for anon on roster_cham_cong" ON roster_cham_cong;
CREATE POLICY "Allow all for anon on roster_cham_cong" ON roster_cham_cong FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE nhan_vien ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for anon on nhan_vien" ON nhan_vien;
CREATE POLICY "Allow all for anon on nhan_vien" ON nhan_vien FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE thang_luong ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for anon on thang_luong" ON thang_luong;
CREATE POLICY "Allow all for anon on thang_luong" ON thang_luong FOR ALL USING (true) WITH CHECK (true);

-- Reload schema cache for PostgREST
NOTIFY pgrst, 'reload schema';
`;

export async function clearSupabaseData() {
  await clearSupabaseRosterData();
  const { error: error2 } = await supabase.from("nhan_vien").delete().neq("id", 0);
  const { error: error3 } = await supabase.from("thang_luong").delete().neq("id", 0);

  if (error2 && !error2.message.includes('relation "nhan_vien" does not exist')) {
    throw new Error(`Lỗi xóa bảng nhan_vien: ${error2.message}`);
  }
  if (error3 && !error3.message.includes('relation "thang_luong" does not exist')) {
    throw new Error(`Lỗi xóa bảng thang_luong: ${error3.message}`);
  }
}

export async function clearSupabaseRosterData() {
  const { error } = await supabase
    .from("roster_cham_cong")
    .delete()
    .neq("id", 0);
  if (error && !error.message.includes('relation "roster_cham_cong" does not exist')) {
    throw new Error(`Lỗi xóa bảng roster_cham_cong: ${error.message}`);
  }
}

async function removeStaleSupabaseRosterRows(activeUniqueIds: Set<string>) {
  const existingRows: Array<{ id: number; unique_id: string | null }> = [];
  const pageSize = 1000;
  let from = 0;

  while (true) {
    const { data, error } = await supabase
      .from("roster_cham_cong")
      .select("id,unique_id")
      .order("id", { ascending: true })
      .range(from, from + pageSize - 1);
    if (error) {
      throw new Error(`Không thể kiểm tra dữ liệu Roster cũ: ${error.message}`);
    }
    if (!data || data.length === 0) break;
    existingRows.push(...data);
    if (data.length < pageSize) break;
    from += pageSize;
    if (existingRows.length > 250_000) {
      throw new Error("Roster trên Supabase vượt quá giới hạn 250.000 dòng để đối soát an toàn.");
    }
  }

  const staleIds = existingRows
    .filter((row) => !row.unique_id || !activeUniqueIds.has(String(row.unique_id)))
    .map((row) => row.id);

  for (let index = 0; index < staleIds.length; index += 200) {
    const chunk = staleIds.slice(index, index + 200);
    const { error } = await supabase
      .from("roster_cham_cong")
      .delete()
      .in("id", chunk);
    if (error) {
      throw new Error(`Không thể xóa dữ liệu Roster cũ bị nhân bản: ${error.message}`);
    }
  }

  return staleIds.length;
}

export async function syncEmployeesToSupabase(
  employeeData: Record<string, unknown>[],
  onProgress?: (successCount: number, total: number) => void
) {
  const chunkSize = 100;
  let successCount = 0;

  const mappedRows = employeeData.map((e) => {
    const employeeId = String(e.employeeId || e["Mã NV"] || e["ID Number"] || e.employee_id || e.ma_nv || "").trim();
    const fullName = String(e.fullName || e.full_name || e["Name"] || e["Họ tên"] || "").trim();
    const bankAccountNumber = String(e.bankAccountNumber || e.bank_account_number || e["Bank Account"] || e["Bank Account Number"] || "").trim();
    const salaryScale = String(e.salaryScale || e.salary_scale || e["Salary Scale"] || "").trim();
    const business = String(e.business || e["Business"] || "").trim();
    const center = String(e.center || e.l07 || e["L07"] || "").trim();
    const fromVal = String(e.from || e["From"] || "").trim();
    const toVal = String(e.to || e["To"] || "").trim();
    const className = String(e.className || e.class_name || e["Class Name"] || "").trim();
    const noteDays = String(e.noteDays || e.note_days || e["Note"] || "").trim();

    return {
      business,
      center,
      employee_id: employeeId,
      full_name: fullName,
      bank_account_number: bankAccountNumber,
      salary_scale: salaryScale,
      from: fromVal,
      to: toVal,
      class_name: className,
      note_days: noteDays,
      unique_id: employeeId,
      raw_data: e
    };
  }).filter((e) => e.employee_id);

  const total = mappedRows.length;
  if (total === 0) return { successCount: 0, totalRows: 0 };

  for (let i = 0; i < total; i += chunkSize) {
    const chunk = mappedRows.slice(i, i + chunkSize);
    const { error } = await supabase.from("nhan_vien").upsert(chunk, { onConflict: "employee_id" });
    if (error) {
      if (error.message.includes('relation "nhan_vien" does not exist')) {
        throw new Error("Bảng 'nhan_vien' chưa tồn tại trên Supabase. Vui lòng chạy SQL setup trong phần cấu hình Supabase.");
      }
      throw new Error(`Lỗi đồng bộ Nhân viên [${error.code}]: ${error.message}`);
    }
    successCount += chunk.length;
    if (onProgress) onProgress(successCount, total);
  }

  return { successCount, totalRows: total };
}

export async function syncSalaryScalesToSupabase(
  salaryScaleData: Record<string, unknown>[],
  onProgress?: (successCount: number, total: number) => void
) {
  const chunkSize = 100;
  let successCount = 0;

  const mappedRows = salaryScaleData.map((s) => {
    const s_code = String(s.sCode || s["S Code"] || s.s_code || s.salaryScale || s["Salary Scale"] || "").trim();
    const academic_price = Number(s.academicPrice || s["Academic Price"] || s.academic_price || s.don_gia_gio || 0);
    const base_salary = Number(s.baseSalary || s["Base Salary"] || s.base_salary || s.luong_co_ban || 0);
    const total_salary = Number(s.totalSalary || s["Total Salary"] || s.total_salary || s.tong_luong || 0);
    const deduction_hours = Number(s.deductionHours || s["Deduction Hours"] || s.deduction_hours || s.gio_khau_tru || 0);

    return {
      s_code,
      academic_price,
      base_salary,
      total_salary,
      deduction_hours,
      unique_id: s_code,
      raw_data: s
    };
  }).filter((s) => s.s_code);

  const total = mappedRows.length;
  if (total === 0) return { successCount: 0, totalRows: 0 };

  for (let i = 0; i < total; i += chunkSize) {
    const chunk = mappedRows.slice(i, i + chunkSize);
    const { error } = await supabase.from("thang_luong").upsert(chunk, { onConflict: "s_code" });
    if (error) {
      if (error.message.includes('relation "thang_luong" does not exist')) {
        throw new Error("Bảng 'thang_luong' chưa tồn tại trên Supabase. Vui lòng chạy SQL setup trong phần cấu hình Supabase.");
      }
      throw new Error(`Lỗi đồng bộ Thang lương [${error.code}]: ${error.message}`);
    }
    successCount += chunk.length;
    if (onProgress) onProgress(successCount, total);
  }

  return { successCount, totalRows: total };
}

export async function syncRosterToSupabase(
  rosterData: Record<string, unknown>[],
  onProgress: (successCount: number, total: number) => void
) {
  const chunkSize = 200; // Reduced from 1000 to avoid payload size/timeout issues
  let successCount = 0;

  // Helper to get value from object with multiple possible keys (case-insensitive)
  const getVal = (obj: Record<string, unknown>, keys: string[]) => {
    if (!obj) return "";
    for (const k of keys) {
      if (obj[k] !== undefined && obj[k] !== null && obj[k] !== "") return obj[k] as string | number;
    }
    // Case-insensitive search
    const objKeys = Object.keys(obj);
    for (const k of keys) {
      const target = k.toLowerCase();
      const foundKey = objKeys.find(ok => ok.toLowerCase() === target);
      if (foundKey && obj[foundKey] !== undefined && obj[foundKey] !== null && obj[foundKey] !== "") return obj[foundKey] as string | number;
    }
    return "";
  };

  // Helper to format date strings to YYYY-MM-DD
  const formatDateForDb = (dateStr: string): string => {
    if (!dateStr) return "";
    const cleaned = dateStr.replace(/^[a-zA-Z]{3,4}\s+/, "").trim(); // Remove "Fri ", "Mon ", etc.
    
    const matchYmd = cleaned.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);
    if (matchYmd) {
      const p2 = parseInt(matchYmd[2], 10);
      const p3 = parseInt(matchYmd[3], 10);
      let m = p2, d = p3;
      if (p2 > 12) { d = p2; m = p3; }
      return `${matchYmd[1]}-${m.toString().padStart(2, '0')}-${d.toString().padStart(2, '0')}`;
    }

    const matchDmy = cleaned.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})/);
    if (matchDmy) {
      const p1 = parseInt(matchDmy[1], 10);
      const p2 = parseInt(matchDmy[2], 10);
      let d = p1, m = p2;
      if (p2 > 12) { d = p2; m = p1; }
      return `${matchDmy[3]}-${m.toString().padStart(2, '0')}-${d.toString().padStart(2, '0')}`;
    }

    const matchYmdSlash = cleaned.match(/^(\d{4})[/-](\d{1,2})[/-](\d{1,2})/);
    if (matchYmdSlash) {
      const p2 = parseInt(matchYmdSlash[2], 10);
      const p3 = parseInt(matchYmdSlash[3], 10);
      let m = p2, d = p3;
      if (p2 > 12) { d = p2; m = p3; }
      return `${matchYmdSlash[1]}-${m.toString().padStart(2, '0')}-${d.toString().padStart(2, '0')}`;
    }

    return cleaned;
  };

  // Deduplicate roster data by unique_id before syncing to avoid chunk conflicts
  const uniqueRowsMap = new Map<string, Record<string, unknown>>();
  const dedupedRosterData = dedupeTimesheetRosterRows(rosterData);
  dedupedRosterData.forEach((r) => {
    const ma_nv = String(getVal(r, ["ma_nv", "ID Number", "employeeId", "ID", "Mã NV", "Teacher ID", "Emp ID", "Staff ID", "manv", "id nv", "staff code", "emp code"])).trim();
    const rawNgay = String(getVal(r, ["ngay", "Date", "date", "Ngày", "TK_Date", "Session Date", "SessionDate", "Ngày học", "Date of Class", "ScheduleDate", "Ngày làm việc"])).trim();
    const ngay = formatDateForDb(rawNgay) || rawNgay;
    const rawGioVao = String(getVal(r, ["gio_vao", "From", "from", "Giờ vào", "gio vao", "Start", "start time", "Start Time", "từ", "Từ", "start_time"])).trim();
    const gio_vao = rawGioVao || "00:00";
    const gio_ra = String(getVal(r, ["gio_ra", "To", "to", "Giờ ra", "gio ra", "End", "end time", "End Time", "đến", "Đến", "end_time"])).trim();
    
    if (!ma_nv && !ngay) return;

    const unique_id = createStableTimesheetRowId(r, "SUPABASE");
    
    uniqueRowsMap.set(unique_id, {
      l07: String(getVal(r, ["l07", "trung tâm (l07)", "cơ sở (l07)", "mã l07", "ma l07", "center code", "office code", "Center", "Trung tâm", "trung tam", "Cơ sở", "co so", "center", "chi nhánh", "mã trung tâm", "ma trung tam", "location", "site", "branch", "region", "vùng", "miền", "khu vực", "campus", "office", "area", "ma co so", "mã ae", "ma ae", "ae", "ae code", "ae_code", "ae name", "ae_name", "ae-code"])).trim(),
      center: String(r.center || r.maAE || getVal(r, ["center", "maAE", "mã ae", "ae", "ae code", "cơ sở", "trung tâm", "chi nhánh", "center code", "office code"])).trim(),
      business: String(getVal(r, ["business", "Business", "Khối", "Bộ phận", "BU"])).trim(),
      ma_nv,
      full_name: String(getVal(r, ["full_name", "Full Name", "Họ tên", "Name", "Họ và tên", "fullName"])).trim(),
      ngay,
      type: String(getVal(r, ["type", "code", "task code", "activity code", "type code", "type_code", "typecode", "Type", "Loại", "Task Type", "taskType"])).trim(),
      class: String(getVal(r, ["class", "class code", "class_code", "classcode", "Class", "Lớp", "Class Code", "classCode"])).trim(),
      gio_vao,
      gio_ra,
      duration: Number(getVal(r, ["duration", "Duration", "Số giờ", "Working Hours", "workingHours"])) || 0,
      notes: String(getVal(r, ["notes", "Notes", "Ghi chú"])).trim(),
      charge_to_center_mkt: String(getVal(r, ["chargeToCenterMkt", "charge_to_center_mkt", "Charge to Center MKT"])).trim(),
      unique_id
    });
  });

  const uniqueRows = Array.from(uniqueRowsMap.values());
  const actualTotal = uniqueRows.length;

  if (actualTotal === 0) {
    throw new Error("Không có dữ liệu hợp lệ (thiếu Mã NV, Ngày hoặc Giờ vào) để đồng bộ.");
  }

  for (let i = 0; i < actualTotal; i += chunkSize) {
    const chunk = uniqueRows.slice(i, i + chunkSize);
    
    let response;
    let retries = 3;
    while (retries > 0) {
      try {
        response = await supabase
          .from("roster_cham_cong")
          .upsert(chunk, { onConflict: 'unique_id' });
        
        if (response.error && (response.error.message.includes("fetch") || response.error.message.includes("Failed to fetch"))) {
          throw new Error(response.error.message);
        }
        break; // Success or non-network error
      } catch (err: unknown) {
        retries--;
        if (retries === 0) {
          if (err instanceof Error && (err.message.includes("fetch") || err.name === "TypeError")) {
            throw new Error("Không thể kết nối tới Supabase (Failed to fetch). Vui lòng kiểm tra lại URL Supabase trong phần Settings và đảm bảo Project của bạn đang hoạt động (không bị tạm dừng).");
          }
          throw err;
        }
        await new Promise(r => setTimeout(r, 1000)); // Wait 1s before retry
      }
    }

    const { error } = response!;

    if (error) {
      if (error.code === '23503' || error.message.includes("violates foreign key constraint") || error.message.includes("ma_nv_fkey")) {
        throw new Error("Đồng bộ thất bại: Dữ liệu điểm danh chứa mã nhân viên không tồn tại trong danh sách nhân viên của bạn, vi phạm ràng buộc khóa ngoại 'roster_cham_cong_ma_nv_fkey' của Supabase. Vui lòng vào tab Cấu hình Supabase (hoặc tab Setup), sao chép và CHẠY LẠI SQL Setup Script trong SQL Editor của Supabase để tự động loại bỏ ràng buộc khóa ngoại này.");
      }

      if (error.message.includes("unique_nv_ngay") || (error.details && error.details.includes("unique_nv_ngay"))) {
        throw new Error("Bảng của bạn đang có ràng buộc trùng lặp 'unique_nv_ngay' (giới hạn mỗi nhân viên chỉ được có 1 dòng công/ngày). Ràng buộc này không phù hợp với Roster có nhiều ca. Vui lòng copy và chạy lại SQL Setup Script trong phần cấu hình Supabase để tự động loại bỏ ràng buộc này.");
      }

      if (error.message.includes('relation "roster_cham_cong" does not exist')) {
        throw new Error("Bảng 'roster_cham_cong' chưa tồn tại trên Supabase. Vui lòng chạy script SQL setup trong phần cấu hình Supabase của bạn.");
      }

      if (error.message.includes("charge_to_center_mkt")) {
        throw new Error("Thiếu cột 'charge_to_center_mkt' trong bảng Supabase. Vui lòng chạy lại script SQL setup để cập nhật cấu trúc bảng.");
      }

      if (error.code === 'PGRST204') {
        throw new Error(`Thiếu cột trong bảng Supabase: ${error.message}`);
      }
      
      if (error.message.includes("Failed to fetch") || error.message.includes("fetch")) {
        throw new Error("Không thể kết nối tới Supabase (Failed to fetch). Vui lòng kiểm tra lại URL Supabase trong phần Settings và đảm bảo Project của bạn đang hoạt động (không bị tạm dừng).");
      }

      const detail = error.details || error.hint || "";
      throw new Error(`Supabase Error [${error.code}]: ${error.message}${detail ? " - " + detail : ""}`);
    }

    successCount += chunk.length;
    onProgress(successCount, actualTotal);

    await new Promise((resolve) => setTimeout(resolve, 200));
  }

  // The caller supplies the complete active Timesheet snapshot. Reconcile
  // only after every upsert succeeds so legacy random UUID rows cannot be
  // loaded back and multiplied during a later session.
  await removeStaleSupabaseRosterRows(
    new Set(uniqueRows.map((row) => String(row.unique_id))),
  );

  return { successCount, totalRows: actualTotal };
}
